{% set name = "base58" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/keis/base58/archive/v{{ version }}.tar.gz
  sha256: 88fecb0c786f6a84fb81eebdb418f6deba08b9c9d90f49a180793ead9a0348d9

build:
  number: 0
  noarch: python
  entry_points:
    - base58 = base58:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5

test:
  imports:
    - base58
  source_files:
    - test_base58.py
  commands:
    - pip check
    - base58 --help
    - pytest test_base58.py
  requires:
    - pip
    - pytest
    - PyHamcrest

about:
  home: https://github.com/keis/base58
  summary: Base58 and Base58Check implementation
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - step21
